name: linterCheck

on: push

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - name: Checkout code
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
        make install
      env:
        CI: true
    - name: Run linter
      run: |
        make lint
    - name: Test & publish code coverage
